FROM maven:3.9.9-eclipse-temurin-21-jammy AS build
WORKDIR /app
COPY onnoto-backend /app
RUN mvn clean package -DskipTests

FROM openjdk:21-slim
WORKDIR /app
COPY --from=build /app/target/onnoto-backend-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8087
ENTRYPOINT ["java", "-jar", "app.jar"]
