# fly.toml app configuration file generated for onnoto on 2025-05-20T08:06:01+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'onnoto'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8087
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
