[variables]
NIXPACKS_JDK_VERSION = "21"

[phases.setup]
nixPkgs = ["maven", "jdk", "bash", "findutils"]

[phases.build]
cmds = [
    "find /nix/store -name java -type f | grep bin/java",
    "export JAVA_HOME=$(dirname $(dirname $(find /nix/store -name java -type f | grep bin/java | head -1)))",
    "echo $JAVA_HOME",
    "export PATH=$JAVA_HOME/bin:$PATH",
    "cd onnoto-backend && chmod +x mvnw",
    "cd onnoto-backend && JAVA_HOME=$JAVA_HOME PATH=$PATH ./mvnw -v",
    "cd onnoto-backend && JAVA_HOME=$JAVA_HOME PATH=$PATH ./mvnw clean package -DskipTests"
]

[start]
cmd = "cd onnoto-backend && java -Dserver.port=$PORT -jar target/onnoto-backend-0.0.1-SNAPSHOT.jar"