[build]
builder = "nixpacks"
buildCommand = "cd onnoto-backend && chmod +x ./mvnw && ./mvnw package -DskipTests"

[deploy]
startCommand = "cd onnoto-backend && java -jar target/onnoto-backend-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/health"
healthcheckTimeout = 90
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10