[phases.setup]
aptPkgs = ['default-jdk', 'maven']

[phases.build]
cmds = [
    'cd onnoto-backend && chmod +x mvnw',
    'cd onnoto-backend && ./mvnw clean package -DskipTests'
]

[start]
cmd = 'cd onnoto-backend && java -jar target/*.jar'