[phases.setup]
nixPkgs = ["jdk", "maven"]

[phases.install]
cmds = ["cd onnoto-backend && chmod +x mvnw"]

[phases.build]
cmds = ["cd onnoto-backend && ./mvnw clean package -DskipTests"]

[start]
cmd = "cd onnoto-backend && java -jar target/onnoto-backend-0.0.1-SNAPSHOT.jar"