[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y openjdk-21-jdk && export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java)))) && cd onnoto-backend && chmod +x ./mvnw && ./mvnw package -DskipTests"

[deploy]
startCommand = "cd onnoto-backend && java -jar target/onnoto-backend-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/health"
healthcheckTimeout = 90
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10